In [1]:
import pymongo
from pymongo import MongoClient
import json
import datetime
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib notebook

In [2]:
mongo_uri = 'mongodb://stockUser:stockUserPwd@localhost:27017/stock_data' # local mongodb address
dbName = "stock_data" # database name
db = MongoClient(mongo_uri)[dbName]

In [3]:
df = pd.DataFrame(list(db["dailyBrokerPoints"].find({"stockId":"0050"}))).drop(columns="_id")
df[['均價', '買價', '買賣超', '買量', '賣價', '賣量']] = df[['均價', '買價', '買賣超', '買量', '賣價', '賣量']].astype("float")

In [4]:
name_df = pd.DataFrame(list(db["券商代號表"].find()))
foreign_broker_list = name_df.loc[name_df["類別"] != "本土券商", "券商名稱"].dropna().to_list()+ ["台灣巴克萊"]

In [20]:
df["類別"] = df["券商名稱"].apply(lambda x: "外資" if x in foreign_broker_list else "台資")
df = df.set_index("timestamp")

In [136]:
feature_df = pd.DataFrame(index=df.groupby(df.index)["買量"].mean().index)

feature_df["feature_1"] = df.groupby(df.index)[["買量", "賣量"]].apply(parse_1)
feature_df["feature_2"] = df.groupby(df.index)[["買賣超", "stockId"]].apply(parse_2)
feature_df["feature_3"] = df.groupby(df.index)["買量"].mean()
feature_df["feature_4"] = df.groupby(df.index)["買量"].std()
feature_df["feature_5"] = df.groupby(df.index)[["買量"]].apply(parse_5)    
feature_df["feature_6"] = df.groupby(df.index)["買量"].apply(pd.DataFrame.kurtosis)
feature_df["feature_7"] = df.groupby(df.index)["賣量"].mean()
feature_df["feature_8"] = df.groupby(df.index)["賣量"].std()
feature_df["feature_9"] = df.groupby(df.index)[["賣量"]].apply(parse_9)    
feature_df["feature_10"] = df.groupby(df.index)["賣量"].apply(pd.DataFrame.kurtosis)
feature_df["feature_11"] = df.groupby(df.index)["券商名稱"].count()
feature_df["feature_12"] = feature_df["feature_5"]/feature_df["feature_9"]
feature_df["feature_13"] = df.groupby(df.index)["買量", "類別"].apply(parse_13)
feature_df["feature_14"] = df.groupby(df.index)["賣量", "類別"].apply(parse_14)
feature_df["feature_15"] = feature_df["feature_13"] - feature_df["feature_14"]
feature_df["feature_16"] = df.groupby(df.index)["買量", "類別"].apply(parse_16)
feature_df["feature_17"] = df.groupby(df.index)["賣量", "類別"].apply(parse_17)
feature_df["feature_18"] = feature_df["feature_16"] - feature_df["feature_17"]

In [139]:
feature_df.head()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18
timestamp,,,,,,,,,,,,,,,,,,
2016-01-05,-14.0,714,25.284553,161.596236,0.825597,240.260554,25.300813,237.067832,0.980622,164.300797,861,0.841912,16.0,2720.0,-2704.0,21754.0,19064.0,2690.0
2016-01-06,-14.0,770,32.210468,185.045703,0.810519,175.999709,32.226058,391.803598,0.981577,341.552005,898,0.825731,3032.0,8734.0,-5702.0,25893.0,20205.0,5688.0
2016-01-07,755.0,-80,11.473118,126.370719,0.943616,185.262711,7.413978,28.931898,0.730812,122.727702,186,1.291188,0.0,0.0,0.0,2134.0,1379.0,755.0
2016-01-08,-15.0,753,27.706972,143.168683,0.763233,283.409155,27.723312,496.749899,0.977870,793.822527,918,0.780506,0.0,2867.0,-2867.0,25435.0,22583.0,2852.0
2016-01-11,-18.0,-252,10.010622,91.459335,0.934982,262.959244,10.037936,66.544955,0.819522,422.454230,659,1.140888,100.0,321.0,-221.0,6497.0,6294.0,203.0

In [132]:
def gini(array):
    """Calculate the Gini coefficient of a numpy array."""
    # based on bottom eq: http://www.statsdirect.com/help/content/image/stat0206_wmf.gif
    # from: http://www.statsdirect.com/help/default.htm#nonparametric_methods/gini.htm
    array = array.flatten() #all values are treated equally, arrays must be 1d
    if np.amin(array) < 0:
        array -= np.amin(array) #values cannot be negative
    array += 0.0000001 #values cannot be 0
    array = np.sort(array) #values must be sorted
    index = np.arange(1,array.shape[0]+1) #index per array element
    n = array.shape[0]#number of array elements
    return ((np.sum((2 * index - n  - 1) * array)) / (n * np.sum(array))) #Gini coefficient

def parse_1(x): 
    return x["買量"].sum() - x["賣量"].sum()

def parse_2(x): 
    return x.loc[x["買賣超"] > 0, "stockId"].count() - x.loc[x["買賣超"] < 0, "stockId"].count()

def parse_5(x): 
    return gini(x["買量"].values)

def parse_9(x): 
    return gini(x["賣量"].values)

def parse_13(x): 
    return x.loc[x["類別"]=="外資", "買量"].sum()

def parse_14(x): 
    return x.loc[x["類別"]=="外資", "賣量"].sum()

def parse_16(x): 
    return x.loc[x["類別"]!="外資", "買量"].sum()

def parse_17(x): 
    return x.loc[x["類別"]!="外資", "賣量"].sum()

In [142]:
import requests

req = requests.get("https://www.twse.com.tw/brokerService/branchList.html")
branch_df = pd.read_html(req.text)[0]
req = requests.get("https://www.twse.com.tw/brokerService/brokerList?response=html&lang=zh")
broker_df = pd.read_html(req.text)[0]

merge_df = pd.concat([branch_df, broker_df], axis=0)
merge_df["券商名稱"] = merge_df["證券商名稱"].apply(lambda x: x.replace(" ", ""))

merge_df.rename(columns={"證券商代號": "券商代號"})
merge_df = merge_df.drop(columns=["分公司", "證券商名稱"]).set_index("證券商代號")

for_df = pd.DataFrame([{"券商代號":"1360", "券商名稱":"港商麥格理", "類別":"港商"},
{"券商代號":"1380", "券商名稱":"東方匯理", "類別":"法商"},
{"券商代號":"1440", "券商名稱":"美林", "類別":"美商"},
{"券商代號":"1470", "券商名稱":"台灣摩根士丹利", "類別":"美商"},
{"券商代號":"1480", "券商名稱":"美商高盛", "類別":"美商"},
{"券商代號":"1520", "券商名稱":"瑞士信貸", "類別":"瑞士商"},
{"券商代號":"1530", "券商名稱":"港商德意志", "類別":"港商"},
{"券商代號":"1560", "券商名稱":"港商野村", "類別":"港商"},
{"券商代號":"1570", "券商名稱":"港商法國興業", "類別":"港商"},
{"券商代號":"1590", "券商名稱":"花旗環球", "類別":"美商"},
{"券商代號":"1650", "券商名稱":"新加坡商瑞銀", "類別":"新加坡商"},
{"券商代號":"8440", "券商名稱":"摩根大通", "類別":"美商"},
{"券商代號":"8890", "券商名稱":"大和國泰", "類別":"日商"},
{"券商代號":"8900", "券商名稱":"法銀巴黎", "類別":"法商"},
{"券商代號":"8910", "券商名稱":"台灣巴克萊", "類別":"英商"},
{"券商代號":"8960", "券商名稱":"香港上海匯豐", "類別":"港商"}]).set_index("券商代號")

for_df = for_df.drop(columns="券商名稱")

def parse(x): 
    if x is np.nan: 
        return "本土券商" 
    else: 
        return x
    
merge_df = pd.concat([merge_df, for_df], axis=1, sort=False)    
merge_df["類別"] = merge_df["類別"].apply(parse)
merge_df["券商代號"] = merge_df.index

dicts = merge_df.to_dict("records")
db["券商代號表"].create_index([("券商名稱", 1)])
for d in dicts: 
    db["券商代號表"].insert_one(d)